README.md
This documents the most basic "setup" needed to get the bot up and running.
=> Document the startup procedure

lib/pollTravis.js, server.js
Compared to the nodejs.org repo, Travis doesn't pick up newly created PR's from nodejs/readable-stream. Strangely enough it does pick up commits and builds them though.
Therefore these changes adds support for polling Travis builds by commit SHAs rather than PR #id alone. The bot tries to do a smart choice about which polling to use by checking if Travis has had *any* builds triggered by PR's lately, if not if starts to poll by SHA.
Disclaimer for sore eyes: this introduces a lot of duplicated code between polling PR's and SHAs. I'd rather get this up-n-running and clean up the mess later.
Refs https://github.com/nodejs/readable-stream/pull/194#issuecomment-205944477
=> Add support for polling Travis CI builds by SHA

Procfile, lib/github-events.js, package.json, scripts/display-travis-status.js, server.js
<del>Not tested- but should mostly be correct ;)</del>
EDIT: Testing & working!
I'm using a `.env` file like discussed in https://github.com/nodejs-github-bot/github-bot/pull/7#issuecomment-205525555
<del>You'll probably notice that `github-webhook-handler` is referencing my fork- hopefully @rvagg will [accept my PR](https://github.com/rvagg/github-webhook-handler/pull/19) and that can be replaced soon. If not, I can do it a uglier way.</del> EDIT: Needed to go a different direction in the end anyhow.
=> emit github events

lib/pollTravis.js, scripts/display-travis-status.js
Here's a test of a [success status](https://github.com/TestOrgPleaseIgnore/test-github-bot/pull/13), and a [failure status](https://github.com/TestOrgPleaseIgnore/test-github-bot/pull/14).
cc @williamkapke & @phillipj
=> Use GitHub Status API

lib/pollTravis.js
Discussion in https://github.com/nodejs-github-bot/github-bot/pull/15
=> Remove outdated travis commenting logic

lib/github-events.js
/cc @Fishrock123 @williamkapke
=> Log when we've got requests with invalid secrets

lib/pollTravis.js
We've been struggling with PR builds being triggered with commit SHA we have no reference of - seems like some kind of meta merge commit made by GitHub. Therefore our effort of matching builds by the actual commit SHA from PRs doesn't always work.
There's a trivial change included here in 05af2ed which also tries to match commits by their related PR. Fingers crossed this is what we need.
+ reverting the revert (deleting the commenting code)
P.S. this is currently deployed to production.
=> Find commit by PR when polling Travis builds

lib/pollTravis.js
As seen in the nodejs.org repo today https://github.com/nodejs/nodejs.org/pull/647#issuecomment-208940672, the bot might be tripped into reporting status for the previous build/commit.
This aims to fix that issue by always matching commits by their date as well as commit sha or PR number.
Refs #22
=> Also match commits by their commited date when polling Travis

package.json, server.js
The (current) initial version just tries to load all files in the `./scripts` directory. When developing, you want to target just the script you're working on.
This change allows a `glob` argument to be passed in to specify which file(s) to try to load. If it isn't specified, it defaults to `./scripts/**/*.js`.
=> Use globs to load scripts

lib/github-client.js, lib/pollTravis.js
Cherry picked from #6.
Refs https://github.com/nodejs-github-bot/github-bot/pull/6#issuecomment-209700780
/cc @williamkapke
=> Extracted GitHub client for reuseability

README.md, package.json, server.js
I [threw together a relay server](https://github.com/williamkapke/hook-relay) to help with developing the bot. The way it works is you set a `SSE_RELAY` env variable to the url of the relay server that will relay you the events from Github. This removes the need for devs to setup a webhook & routing that points to their local machine... or even worse: deploying to their host, over & over again!
**EDIT**: In the picture above, the repos would likely be `TestOrgPleaseIgnore` not `nodejs`.
[SSE is a very simple/lightweight protocol](https://html.spec.whatwg.org/multipage/comms.html#server-sent-events) that is perfect for this. It even is supported by modern browsers so you can connect and see the raw event stream.
1) Open: https://hook-relay.herokuapp.com/
2) Go to: …
=> Connect to SSE server when SSE_RELAY set

lib/github-events.js, server.js
Having the events emitting in 2 places is not good. The SSE relay is only `github-events` related code - so it makes sense to move it to the `github-events.js` file.
Also, I am now emitting the org, repo, and sender names since will be needed by most listeners.
=> move sse code to github-events

lib/node-labels.js, lib/node-repo.js, package.json, scripts/node-subsystem-label.js, server.js, test/node-labels.test.js
Very much a work in progress ATM, just wanted to get this out there for public scrutiny and work on it the next couple of days.
**Goals**
**UPDATE** In the discussion below, we've decided to only resolve `c++` and `test` labels at first, then add more labels in later iterations of this.
Refs #1
=> Auto label node PR's

lib/node-labels.js, test/node-labels.test.js
This improves the current node core auto PR labelling functionality by supporting these extra labels:
- `doc` for exclusive `doc/*` changes
- `benchmark` for exclusive `benchmark/*` changes
- `v8`, `libuv`, `openssl` etc when having changes in `deps/X/*`
Also ignores changes to `src/node_version.h` to avoid labelling that as `c++` as mentioned in https://github.com/nodejs-github-bot/github-bot/issues/31#issuecomment-214572696.
@jbergstroem @mscdex @Fishrock123 does these labels sound reasonable to you?
Refs #31, https://github.com/nodejs/node/pull/6247
=> Added doc, benchmark and deps/X node core PR labels

lib/node-labels.js, test/node-labels.test.js
This fixes some bad labelling by ensuring that *every* file affected in the PR actually matches an exclusive label when we're checking for exclusive labels.
Refs https://github.com/nodejs/node/pull/6448 https://github.com/nodejs/node/pull/6432
Closes https://github.com/nodejs-github-bot/github-bot/issues/33
=> Fix for bad node core PR exclusive labels.

.travis.yml, app.js, lib/github-client.js, lib/github-events.js, package.json, scripts/ping.js, server.js, test/ping.test.js
As a means of being more confident deploying the bot automatically to production upon merge to master, this ensures the bot at least starts as planned and responds on a trivial GET request.
Did some refactoring to make the bot more testable, most noticeably extracted the `server.listen()` part into it's own file so the `app` could be tested in isolation with explicit control over the server/listening part for testing purposes. Plus not always starting the SSE relay client (which we don't need while testing).
Refs https://github.com/nodejs/build/issues/404.
=> Created smoketest verifying the bot starts

lib/push-jenkins-update.js
Currently we're not logging *which* Jenkins job is trying to push GitHub status updates. That information would be very valuable when debugging.
/cc @jbergstroem
=> Log job name when proxying Jenkins -> GH status

lib/push-jenkins-update.js, scripts/node-jenkins-status.js, test/_fixtures/invalid-payload.json, test/push-jenkins-update.test.js
So far there's been cases when sha, or other required fields of the payload has been missing, but the bot has willingly tried to proxy it as well as responding with a misleading 201 status code.
This at least does some trivial validation and tells you right away if the payload is seen invalid.
=> Validate POST payloads from Jenkins

.travis.yml, lib/node-labels.js, package.json
Allows for more extensibility where labels may be the same. (e.g. more than one `$1` mapping)
Requires Node.js v6.0.0+ for the destructing in the `for of` loop.
cc @phillipj
=> Refactor labels to use Regex-keyed Maps

lib/node-labels.js, test/node-js-subsystem-labels.test.js, test/node-labels.test.js
Depends on https://github.com/nodejs-github-bot/github-bot/pull/41
Does some.. fancy.. mapping for some of the outliers.
Also limits the labels to 4, and just uses `lib / src` at 5.
cc @phillipj
=> Add JS (lib/) subsystem labels

lib/node-labels.js, test/node-js-subsystem-labels.test.js
`buffer` is really separate from `string_decoder` (the latter actually uses the former's functionality), so update the bot's labeling mechanism.
=> labels: fix string_decoder labeling

scripts/display-travis-status.js
Seen in the logs:
```
12:18:09.203 ERROR bot: Got error when retrieving GitHub commits for PR (req_id=.., pr=nodejs/nodejs.org/#754, action=pull_request.opened)
err: {
"code": "400",
"status": "Bad Request",
"message": "Invalid value for parameter 'number': lpinca"
}
```
Bug was introduced in d5fdb5d5a5a6c9705e32524efdb4530f390e73b8.
=> Fix invalid PR argument in Travis poller

lib/node-labels.js, test/node-js-subsystem-labels.test.js, test/node-labels.test.js
This is only done if a PR is *only* modifying a single subsystem's API documentation.
Feel free to reject this and implement it some other way if you don't like how I did this, I just figured it'd be better to submit some kind of PR instead of just creating a feature request issue.
=> labels: add subsystem label for API doc

lib/node-labels.js, test/node-build-label.test.js
This adds support for the `build` label as described in #31.
@jbergstroem in https://github.com/nodejs/node/pull/6247#issuecomment-212211532 you mentioned other stuff in `tools/` aswell . Feel free to provide some examples, and I'll have a look.
=> labels: add "build" label

lib/node-labels.js, test/node-labels.test.js
This prevents changes in `deps/` from getting labelled `lib / src` as seen in https://github.com/nodejs/node/pull/7488.
@Fishrock123 as you implemented `lib / src` in the first place, does this seem good to you?
Closes #52
=> labels: prevent deps from getting "lib / src" label

scripts/display-travis-status.js
As we haven't been using the [TestOrgPleaseIgnore/test-github-bot](https://github.com/TestOrgPleaseIgnore/test-github-bot) repo for testing lately, there's no need to have Travis enabled for it.
This could probably be improved by using an environment variable instead, as this is purely configuration.
=> Cleanup: disable Travis for test-github-bot repo

lib/push-jenkins-update.js, scripts/node-jenkins-status.js, test/_fixtures/error-payload.json, test/_fixtures/invalid-payload.json, test/_fixtures/pending-payload.json, test/_fixtures/pr-commits.json, test/_fixtures/success-payload.json, test/push-jenkins-update.test.js
This introduces the bot finding the correct commit SHAs to use for core PRs, rather than trusting Jenkins to provide SHAs, mainly due to rebasing we often do when running PR jobs.
Also refactored the endpoint Jenkins pushes updates, from one single endpoint to `/node/jenkins/{start,end}`.
P.S. this has been tested in production for a while, and worked pretty well.
/cc @jbergstroem
=> jenkins: finding correct PR commit SHA and new endpoints

lib/node-repo.js, package.json, scripts/node-subsystem-label.js, test/integration/node-labels-webhook.test.js
These changes defer the process of label resolving
to prevent 404 errors from Github API
Closes https://github.com/nodejs/github-bot/issues/79
=> labels: defer resolving labels

CONTRIBUTING.md, GOVERNANCE.md, LICENCE.md, README.md
[As promised](https://github.com/nodejs/TSC/issues/117#issuecomment-237924423) in the [2016-08-11 TSC meeting](https://github.com/nodejs/TSC/issues/127) , here are the boilerplate docs required by the TSC for repos entering the Node.js GitHub org.
=> Add docs required by TSC

lib/node-labels.js
Minor adjustment to the regex matching the base branch a PR is targeted against.
Refs https://github.com/nodejs/github-bot/pull/55#discussion_r77553358
/cc @Fishrock123
=> labels: stricter version match in base branch

lib/node-repo.js, test/integration/node-labels-webhook.test.js, test/integration/push-jenkins-update.test.js, test/read-fixture.js, test/unit/node-repo.test.js
After PR https://github.com/nodejs/github-bot/pull/80 got merged, no labels were added to new PRs.
That regression probably came from the fact that the existing repository labels was fetched and compared to the label names our labelling algorithm thought we should add. The problem is that we compared the whole label meta object (from api.github.com) against a label name (string).
Example of the two different types of objects:
```js
// complete label object
{
"url": "https://api.github.com/repos/nodejs/node/labels/buffer",
"name": "buffer",
"color": "f7c6c7"
}
// label name
"buffer"
```
Comparing two such objects will obviuosly never match.
These changes extracts the existing repo label *names* for comparison, and adds more logging for future debugging purposes.
Closes …
=> labels: fix labels not being added

README.md, app.js
When introducing traceable logs and bunyan in PR #42, it broke the possibility of providing individual scripts to run as second argument to `npm start`.
This fixes that by allowing scripts to be passed in as an environment variables, instead of a CLI argument to `app.js`.
Refs https://github.com/nodejs/github-bot/pull/42
/cc @Fishrock123
=> Fix running individual scripts with `npm start`

lib/node-repo.js, scripts/attempt-backport.js, server.js
This is a script to automatically check if PRs can cleanly land on staging branches in the node repo.
I've been using https://github.com/TestOrgPleaseIgnore/node/pull/29 and https://github.com/TestOrgPleaseIgnore/node/pull/30 to test it and it seems to be working fine now.
This is however a first iteration and I'm sure it can be improved lots.
cc @nodejs/github-bot & @TheAlphaNerd 
Edit: some unresolved questions/issues:
- Should it unlabel if the PR later passes?
=> scripts: new attempt-backport script for PRs

lib/node-repo.js, test/_fixtures/repo-labels-page-2.json, test/unit/node-repo.test.js
This updates `fetchExistingLabels` to fetch *all* labels from GitHub, rather
than just the first 100 labels. This allows the bot to work correctly now
that the repo has more than 100 labels.
Refs: https://github.com/nodejs/node/issues/9841
Since `node-repo` now uses the `githubClient.hasNextPage()` function, this commit also updates the stubs in the corresponding tests to avoid throwing an error when that function is called.
=> fetch multiple pages of labels if necessary

lib/node-labels.js, test/unit/node-labels.test.js
This PR fixes an issue where vcbuild.bat changes were not labeled with 'build' and an issue with some label regexps where dots in filenames were not escaped.
Ref: https://github.com/nodejs/github-bot/issues/88#issuecomment-265287236
=> labels: fix build label

lib/node-repo.js
This is a precursor to two major improvements to the attempt-backport script.
Would like to get this landed tomorrow morning so I can work on having labels only add once, and also having the bot remove it's own labels when appropriate.
=> node-repo: refactor out fetchExistingThenUpdatePr

scripts/attempt-backport.js
Not 100% sure this matters but I'd rather be safe. Noticed this with some `git status` inbetween.
=> attempt-backport: git clean -fd after checkout

scripts/attempt-backport.js
- Resetting *before* checkout is probably actually faulty logic as
described in
https://github.com/nodejs/github-bot/issues/100#issuecomment-267359637
- Resetting after checkout is unnecessary because we check out the
origin/ branch so the HEAD becomes detached.
=> attempt-backport: simplify git steps

lib/node-repo.js, scripts/attempt-backport.js
Should fix https://github.com/nodejs/github-bot/issues/100#issuecomment-266113411 while also giving a way to see when a PR update has changed the backportability.
This was always on the plans, I just hadn't gotten to it before.
cc @phillipj and maybe also @TheAlphaNerd 
I don't really trust myself that it'l work without testing though, but I have a plan on how to test the script, so I'm going to do that next and then rebase this ontop.
=> attempt-backport: unlabel and clean labeling

lib/node-labels.js, test/unit/node-labels.test.js
Ref: https://github.com/nodejs/node/issues/10625
=> labels: add url-whatwg labels for WHATWG URL PRs

scripts/attempt-backport.js
There's been some concerns about auto labelling `dont-land-on-*` labels lately, especially since the bot is often wrongly adding these labels ATM. Therefore temporarily disabling that functionality to avoid further damage.
Refs https://github.com/nodejs/github-bot/issues/116
=> attempt-backport: temporary disable dont-land-on-* labels

scripts/attempt-backport.js
We've seen a lot of patches not applied cleanly by the bot, which in fact
should have landed without trouble, at least with 3-way merges enabled.
This trivial change enables fallback to 3-way merge when a patch
doesn't apply cleanly when running `git am`.
Should we give this a try before possibly disabling the attempt-backport labels?
Refs https://github.com/nodejs/github-bot/issues/116
/cc @mscdex @MylesBorins @Fishrock123
=> attempt-backport: enable 3-way merge for git am

README.md, app.js, lib/logger.js, logs/.gitignore
The main objective behind these changes are to not write logs into the project's `./logs` directory, cause that ends up being deleted whenever the bot is re-deployed. Having some days of historic logs are very valuable while debugging any issue.
Requires deployment changes: https://github.com/nodejs/build/pull/602
=> logs: configurable logs directory with $LOGS_DIR

scripts/jenkins-status.js, test/integration/push-jenkins-update.test.js
This changes allows [citgm](https://github.com/nodejs/citgm) builds to push updates like we already do for nodejs/node. That is done by making the Jenkins status update endpoints more generic, resolving the repository name from an URL parameter.
In practise this means the endpoints stay the same, but configurable:
- `/node/jenkins/start`
- `/citgm/jenkins/start`
Repository names are validated against a whitelist.
Refs https://github.com/nodejs/github-bot/issues/82#issuecomment-276715266
/cc @jbergstroem @gdams
=> jenkins: allow citgm builds to push Jenkins build updates

lib/node-labels.js, test/unit/node-labels.test.js
This updates the label used for inspector-related changes and makes test/cctest changes more accurate now that there are other, non-inspector tests in there.
=> labels: update labeling

lib/node-repo.js, package.json
Trying to get around some intermittent GitHub API 404 failures, probably due to a race condition where the API hasn't yet got to update its PR cache or something similar.
Refs https://github.com/nodejs/github-bot/issues/88#issuecomment-288319518
=> labels: retry request for PR files if GitHub request fails

README.md, lib/bot-username.js, lib/github-events.js, scripts/trigger-jenkins-build.js
Putting this out for public scrutiny to show there is some kind of progress.
The main goal is to get the bot to kick off a Jenkins build triggered by a collaborator commenting in a PR, mentioning the bot.
Refs https://github.com/nodejs/github-bot/issues/82
=> Kicking off Jenkins build triggered by comment

lib/node-labels.js, test/unit/node-labels.test.js
The `lib / src` label bucket / limit does currently not work on files in `src/`.
Closes https://github.com/nodejs/github-bot/issues/137
=> labels: fix lib/src bucket for src/ changes

README.md, scripts/jenkins-status.js
This is needed to ensure not everyone on the internet can push an inline status to any PR if they know the bot URL.
@jbergstroem does this seem sufficient?
Closes https://github.com/nodejs/github-bot/issues/61
=> jenkins: whitelist IPs allowed to push status changes

lib/node-labels.js
=> labels: map dont-land-on-v4(6).x for napi

lib/push-jenkins-update.js, test/_fixtures/pull-requests-commits-page-1.json, test/_fixtures/pull-requests-commits-page-104.json, test/unit/push-jenkins-update.test.js
When pushing Jenkins status to a PR, we need to reference the commit SHA the inline GitHub PR status relates to.
These changes fixes a bug when handling enormous PRs with more than 100 commits (e.g. https://github.com/nodejs/node/pull/9745), where we have to paginate commits results for that PR to find the last commit SHA.
Fixes https://github.com/nodejs/github-bot/issues/97
=> jenkins: paginate PR commits to find the latest commit

scripts/jenkins-status.js
Goes along with a PR in nodejs/build to add a http-parser Jenkins pipeline job.
=> jenkins: add support for http-parser jenkins jobs

scripts/display-travis-status.js
This enables travis intergrations to repos that need it that I am aware of.
cc @phillipj
=> travis: add nan, llnode and node-core-utils

scripts/jenkins-status.js
After the Jenkins IP whitelist was activated, the inline PR status reports for nodejs/node seems to be broken.
Seems like the issue here is that IPv4 remote addresses are converted to IPv6, which wasn't expected too happen.. Stripping any IPv6 parts off the remote addresses should make our IPv4 comparisons work as expected.
Refs https://github.com/nodejs/build/issues/1016
Refs https://github.com/nodejs/build/pull/985
/cc @maclover7
=> jenkins: handle IPv4 remote address converted to IPv6

scripts/trigger-jenkins-build.js, test/integration/trigger-jenkins-build.test.js
This will start a CI build on all new pull requests in nodejs/node, that
are opened by project collaborators
cc @joyeecheung
=> jenkins: start CI run on new pull requests

app.js, package.json
Thought I'd do a rounds of much needed cleanup on this bot, starting with the logs.
So far we have been logging absolutely *all* finished requests which results in a lot of noise in logs.
Local example:
```
$ npm start
..
12:13:32.529Z  INFO bot: Listening on port 3000
12:13:34.468Z  INFO bot: request finish (req_id=8812b800-6bde-11e8-add8-f393315a261f, duration=3.191551, req.query={}, req.remoteAddress=::1, req.remotePort=63894)
GET /ping HTTP/1.1
host: localhost:3000
user-agent: curl/7.54.0
accept: */*
--
HTTP/1.1 200 OK
X-Powered-By: Express
X-Request-Id: 8812b800-6bde-11e8-add8-f393315a261f
Date: Sat, 09 Jun 2018 12:13:34 GMT
Connection: keep-alive
Content-Length: 4
```
Personally cannot remember once where this request information has actually been valuable. If it turns out I'm …
=> Stop logging all finished requests to reduce log noise

scripts/jenkins-status.js, test/_fixtures/jenkins-staging-failure-payload.json, test/integration/push-jenkins-update.test.js
Another long standing cleanup to reduce the errors logs we've seen from the bot.
We have for a long time seen errors logged when Jenkins tells the bot to report inline pull requests statuses, when the build in question is not related to a pull request, but an ordinary branch like the `v8.x-staging` branch.
In short the error raised by github.com said we couldn't fetch commits related to pull request "v8.x-staging". It expects a pull request number to be provided when fetching those commits.
These changes checks if the git reference provided by Jenkins does in fact point to a pull request, if not the incoming request from Jenkins gets a `400 Bad Request` as response.
```
13:01:11.244 ERROR bot: Got error when retrieving GitHub commits for PR (req_id=78e986d9-6c52-485c-bac2-64c2797a7a40, …
```
=> Ignore Jenkins builds not related to pull requests

app.js, server.js
Whenever unhandled errors are raised, it's especially important for us to get some hints of what happened. In a perfect world these kinds of errors shouldn't happen, but ofcourse they do for time to time..
The last time we had this kinds of error, there were no errors visible in the logs, other than seeing that the bot process seemed to restart more than usual.
While working in these changes, I found that the default unhandled error handler in express.js, writes the error to stdout, not into the log log files we've write through via bunyan.
With these changes in place we'll get something like this in the logs:
```
19:16:26.303Z FATAL bot: Unchaught exception, terminating bot process immediately
ReferenceError: invokingNoneExistentFunction is not defined
at Promise.resolve.then …
```
=> Log unhandled errors that occur upon startup or handling HTTP requests

scripts/trigger-jenkins-build.js, test/integration/trigger-jenkins-build.test.js
Was posting the API url for the build, now posts the
correct Blue Ocean url for the build.
Changes environment variable since we do not know what the url for the
build will be based on the API response.
=> jenkins: comment correct url

lib/node-labels.js, test/unit/node-labels.test.js
These apis were backported to v6.x
=> chore: don't apply dont-land labels for 6.x napi and url

lib/node-labels.js, test/unit/node-labels.test.js
Nothing will ever land on 4.x ever again, so there's no need for the
dont-land-on-v4.x label. After this PR lands, hopefully it can be
removed from the GitHub interface.
=> remove dont-land-on-v4.x

lib/node-repo.js, test/_fixtures/pull-request-events-2.json, test/_fixtures/pull-request-events.json, test/unit/node-repo.test.js
Fixes the following error occurring in production, likely happening due
to the recent bump in dependencies.
```
10:49:01.780 FATAL bot: Unchaught exception, terminating bot process immediately
TypeError: events[Symbol.iterator] is not a function
at githubClient.issues.getEvents (/home/iojs/github-bot/lib/node-repo.js:163:23)
at /home/iojs/github-bot/node_modules/github/lib/index.js:912:9
at callCallback (/home/iojs/github-bot/node_modules/github/lib/index.js:738:9)
at IncomingMessage.<anonymous> (/home/iojs/github-bot/node_modules/github/lib/index.js:810:13)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:978:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback …
```
=> node-repo: fix getBotPrLabels

app.js
- Fix typing mistake: `satefy` --> `safety`.
=> Fix comment typo

.editorconfig
`indent_style` is applied to all the files based on `[*]` entry. We
don't have to specify the same for `package.json` explicitly.
=> remove redundant indent_style from editorconfig

server.js
If the environment variable NODE_REPO_DIR is defined and the spawnSync
returns a non-zero code, then `logger` is used to log the response. But
it is not assigned any value yet, as it is in TDZ.
=> avoid ReferenceError with logger

scripts/trigger-jenkins-build.js
The existing code assumes that the credentials are already in base64,
but they are actually not. The code has to read the credentials in plain
text and base 64 encode them.
Ref: https://github.com/nodejs/github-bot/pull/206#discussion_r236054041
---
@maclover7 @phillipj
=> scripts: fix reading credentials for jenkins

.travis.yml
As a precursor to upgrading the Node.js version we run on the github-bot server, this updates the version used by Travis CI when running our tests.
=> Bump Node.js version from 6 to 8 on Travis CI

package-lock.json
Update handlebars in package-lock.json to eliminate a warning from `npm
audit`.
=> update handlebars dev dependency

package-lock.json, package.json
This closes a low-severity security issue in the developer dependency,
so it's not exploitable in the deployed bot, but we should still upgrade
of course.
Refs: https://nvd.nist.gov/vuln/detail/CVE-2018-16492
=> update supertest to 3.4.2

lib/node-labels.js, test/unit/node-labels.test.js
I've found that we need to add `report` label to these PRs manually now.
> https://github.com/nodejs/node/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Areport
=> labels: add "report" label

.travis.yml
While looking for some low hanging chores to do, I stumbled upon `.travis.yml`. Thought we might as well tell Travis to cache the npm dependencies to speed up our builds.
Knowing we've got the entire dependency tree locked down with `package-lock.json`, it can't hurt to cache them, right?
Refs https://docs.travis-ci.com/user/caching/#npm-cache
=> Cache npm dependencies in Travis CI

lib/node-labels.js, test/unit/node-labels.test.js
The PRs affected `worker` module need to be labeled manually at present.
Refs: https://github.com/nodejs/node/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Aworker
=> labels: add "worker" label

lib/push-jenkins-update.js, scripts/jenkins-status.js, test/integration/push-jenkins-update.test.js
*This is a precursor to fixing #212.*
These changes are primarily done so we can get more reliable integration tests. Previously the incoming requests was responded to, before we knew whether or not the Jenkins status has been successfully pushed to GitHub.
That makes it challenging to know when we can assert what we want to verify in integration tests, as we don't know when the entire operation has finished.
Although the previous approach worked in practise when run in production, it should be just as important to have reliable tests that we can rely on when doing changes going forward.
=> Improve integration tests for pushing Jenkins statuses

lib/github-comment.js, lib/push-jenkins-update.js, scripts/trigger-jenkins-build.js, test/_fixtures/jenkins-test-pull-request-success-payload.json, test/integration/push-jenkins-update.test.js
These changes posts a CI style comment to PR's whenever Jenkins reports that node-test-pull-request builds has started.
Closes https://github.com/nodejs/github-bot/issues/212
/cc @nodejs/github-bot 
*P.S. temporary non-master base branch as these changes builds on https://github.com/nodejs/github-bot/pull/222.*
=> Post CI comment in PR for node-test-pull-request builds

.travis.yml, package-lock.json
To be consistent with the Node.js version we're running in production.
Refs nodejs/build#1741
=>  Bump Node.js version from 8 to 10 on Travis CI

scripts/trigger-jenkins-build.js
We've seen some error logs in production suggesting that we get errors back from Jenkins when triggering builds, as the result is `null | undefined`. Destructuring fields out of that result causes unchaught exceptions, meaning the bot process dies.
Therefore postponing the destructuring until we're confident the build didn't result in an error.
/cc @nodejs/github-bot @richardlau
Refs https://github.com/nodejs/github-bot/issues/235
=> Destructure Jenkins build result after knowing it's not an error

lib/github-comment.js, lib/github-graphql-client.js, package-lock.json, package.json, test/_fixtures/pull-request-three-comments-gql.json, test/_fixtures/pull-request-zero-comments-gql.json, test/integration/push-jenkins-update.test.js, test/unit/github-comment.js
=> Try to find a comment to edit before creating

scripts/trigger-jenkins-build.js
As the bot does not have permission to trigger Jenkins Lite-CI builds for some reason at the moment, and there's feedback about these error comments not being useful to collaborators anyways, those comments are muted for now.
Ideally github-bot maintainers should get notified about these errors, as they're obviously not meant to be raised at all. But using node core collaborators as proxy, manually telling bot maintainers about errors surely isn't ideal either.
Refs https://github.com/nodejs/github-bot/issues/238
Refs https://github.com/nodejs/github-bot/issues/235#issuecomment-500659506
/cc @nodejs/github-bot @cjihrig @sam-github
=> Don't post PR comment on errors when triggering Lite-CI

lib/push-jenkins-update.js
*FYI PR that gets merged ASAP because of its trivialness.*
While having a look at recent error logs, this fatal log stood out:
```
02:48:11.721 FATAL bot: Unchaught exception, terminating bot process immediately
TypeError: Cannot read property 'data' of undefined
at githubClient.pullRequests.getCommits (/.../github-bot/lib/push-jenkins-update.js:92:29)
at module.exports.sendError (/.../github-bot/node_modules/github/lib/index.js:874:7)
at /.../github-bot/node_modules/github/lib/index.js:882:21
at callCallback (/.../github-bot/node_modules/github/lib/index.js:738:9)
at IncomingMessage.<anonymous> (/.../github-bot/node_modules/github/lib/index.js:807:13)
at IncomingMessage.emit (events.js:194:15)
at endReadableNT (_stream_readable.js:1125:12)
at process._tickCallback …
```
=> jenkins: check successful response before reading

lib/node-labels.js
Resolves: https://github.com/nodejs/modules/issues/460
Perhaps changing the name of this label to `esm` would save effort in the long run.
/cc @MylesBorins
=> labels: add ES Modules

app.js, lib/github-comment.js, lib/github-events.js, lib/node-repo.js, package-lock.json, package.json, scripts/node-subsystem-label.js, scripts/trigger-jenkins-build.js, server.js, test/_fixtures/repo-labels-page-2.json, test/_fixtures/repo-labels.json, test/integration/node-labels-webhook.test.js, test/integration/ping.test.js, test/integration/push-jenkins-update.test.js, test/integration/trigger-jenkins-build.test.js, test/unit/node-repo.test.js
**TLDR;** upgrading the package we use to talk to github.com causes integrations tests to break, and those tests are currently unreliable.
The package we're using to talk to github.com uses a deprecated authentication mechanism that I regularly get emails about: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/.
While naively trying to upgrade that package, I stumbled opened up a can of worms that I want to fix properly first...
**Make integration tests execute all external API request expectations**
Previously only a few of the external API request expectations setup with [nock.js](https://github.com/nock/nock) has been run (details explained in the long story below).
How we run those expectations was introduced in the beginning of this project, a …
=> Respond to incoming HTTPS requests when all work is done

lib/node-labels.js
As per discussion on GitHub it does not appear that QUIC is intended
to be backported to v14.x, add appropriate label.
/cc @jasnell to confirm
=> label: mark all quic change as `dont-land-v14.x`

lib/github-client.js, package-lock.json, package.json
`github` has been renamed to `@octokit/rest`. Also bumped to ^v15 as there were no significant breaking changes before ^v16. Upgrading to v16 will require more effort on our side, including:
- Change all GitHub API calls from callback-style to Promise-style
- Rework tests so we don't use sinon to replace GitHub methods as sinon will prevents GitHub deprecation warnings. Use nock instead
- Increase test coverage to include all GitHub API calls
- Fix deprecation warnings (preferably one by one so it's easier to revert if the bot breaks)
Ref: https://github.com/octokit/rest.js/releases/tag/v14.0.0
Ref: https://github.com/octokit/rest.js/releases/tag/v15.0.1
=> chore(deps): replace `github` with `@octokit/rest`

lib/node-repo.js, lib/push-jenkins-update.js, package-lock.json, package.json, test/integration/node-labels-webhook.test.js, test/unit/node-repo.test.js, test/unit/push-jenkins-update.test.js
Resolved all remaining deprecations on v15 (convert everything to promises because callbacks were removed), upgraded to v16, fixed tests (the payload format of one request changed and nock was not matching it anymore). I already fixed some deprecations on v16, but didn't commit yet so that the PR is not overwhelming. With this PR we'll have access to [createDispatchEvent](https://github.com/octokit/rest.js/releases/tag/v16.29.0), which means it will unblock #272.
P.S.: Each commit converts one callback-based function into Promises/async, so the best way to read this PR is going on each commit individually.
=> feat: upgrade octokit to 16

.github/workflows/test.yml, .travis.yml
Primarily as a precursor to upgrading the Node.js version on the server where @nodejs-github-bot runs from v10 -> v14, running tests on v14 in CI is valuable.
Also added Node.js 15 to the mix as it's worth getting early heads up if there are any upcoming issues before considering an upgrade.
The transition to GitHub Actions is done because it's convenient and there's been significant use of Actions in the Node.js org lately.
=> Replace Travis CI with GitHub Actions + more Node.js versions

lib/github-client.js, lib/github-comment.js, lib/node-repo.js, lib/push-jenkins-update.js, test/unit/node-repo-owners.test.js, test/unit/node-repo.test.js, test/unit/push-jenkins-update.test.js
These changes fixes the majority of deprecation warnings seen when currently running our tests, as can be seen in the last run on `master` branch: [last Travis CI run](https://travis-ci.com/github/nodejs/github-bot/builds/183960087)
Aside from the warnings seen in tests, I'm hoping it'll avoid the deprecation emails we've been getting related to the `?access_token` query parameter used for authentication, since these changes does authentication slightly different (inline with recent [Octokit authentication docs](https://octokit.github.io/rest.js/v16#authentication)).
_P.S. might be worth reviewing each commit separately._
Refs https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param
=> Fix deprecated Octokit warnings

lib/jenkins-events.js, scripts/event-relay.js, test/integration/event-relay-to-github-actions.test.js
These changes are meant to allow us to write GitHub Actions in selected repositories in the nodejs github organization, as a reaction to Jenkins events.
It works by dispatching repository events, which we can use as triggers for GitHub Action workflows.
Here's a concrete repository dispatch event caused by the Jenkins job `node-test-commit-osx`:
```
event_type: jenkins.node-test-commit-osx.start or jenkins.node-test-commit-osx.end
client_payload:
{
"identifier": "node-test-commit-osx",
"status": "success",
"message": "tests passed",
"commit": "8a5fec2a6bade91e544a30314d7cf21f8a200de1",
"url": "https://ci.nodejs.org/job/node-test-commit/3157/",
"ref": "refs/pull/12345/head"
}
```
Refs:
* #264
* [GitHub Action docs: repository_dispatch](https://docs.github.com/en/free-pro-team@latest/actions …
=> Relay Jenkins events to Github Action workflows

lib/node-labels.js, test/unit/node-labels.test.js
This will make doc updates to webcrypto.md (part of the crypto subsystem) labeled appropriately.
=> fix: label doc/api/webcrypto.md as crypto doc

lib/node-labels.js, test/unit/node-build-label.test.js, test/unit/node-js-subsystem-labels.test.js, test/unit/node-labels.test.js
Make the bot add a `needs-ci` label to all PRs that make changes to files that affects the `node` binary.
Refs: https://github.com/nodejs/node/pull/37308
=> feat: add `needs-ci` label

lib/jenkins-events.js
Been seeing a lot of these errors lately:
```json
{
"name": "bot",
"hostname": "infra-rackspace-debian8-x64-1",
"pid": 2704,
"req_id": "081c1880-7883-11eb-88cc-b7c6efa14646",
"identifier": "node-test-pull-request",
"event": "end",
"level": 20,
"msg": "Relaying jenkins.node-test-pull-request.end to nodejs/node",
"time": "2021-02-26T22:36:13.705Z",
"v": 0
}
{
"name": "bot",
"hostname": "infra-rackspace-debian8-x64-1",
"pid": 2704,
"req_id": "081c1880-7883-11eb-88cc-b7c6efa14646",
"identifier": "node-test-pull-request",
"event": "end",
"level": 50,
"err": {
"message": "Converting circular structure to JSON\n    --> starting at object with constructor 'Timeout'\n    |     property '_idlePrev' -> object with constructor 'TimersList'\n    --- property '_idleNext' closes the circle",
"name": …
```
=> Bugfix Jenkins -> GitHub Actions relay by avoiding circular reference

lib/node-repo.js, test/unit/node-repo-owners.test.js
_@mmarchini sorry I didn't realise I had broken this until now.._
Turns out the nodejs/node repo owners functionality has been broken for quite some time. When upgrading `@octokit/rest` and avoiding a deprecation warning back in November 2020, the owners functionality stopped working.
Tracked this down by searching for the latest `Review requested: ..` comment found in nodejs/node, which was one day before the said github-bot changes rolled out.
The culprit seems to the `.number -> .pull_number` transition in https://github.com/nodejs/github-bot/commit/7b4ac859952163479b2afe159cf0ff29416b37bb, especially related to listing changes files in a PR when figuring out which owners to ping.
This microscopic change, removing the `.pull_number` field from the options used in …
=> Bugfix for ping repo owners after `@octokit/rest` upgrade

README.md
The Heroku free tier is gone or going away.
We've security-related issues with abandoned herokuapp.com links so removing it (even though it's not a link here).
=> replace herokuapp with example.com

lib/push-jenkins-update.js
Fixes: https://github.com/nodejs/github-bot/issues/374
=> fix: use authenticated GitHub client for Jenkins updates

server.js
glob@9 no longer exports `sync()`.
Fixes: https://github.com/nodejs/github-bot/issues/376
Refs: https://github.com/isaacs/node-glob/issues/493
Refs: https://github.com/nodejs/github-bot/pull/372
=> fix: replace `glob.sync` for glob@9

server.js
Refs: https://github.com/nodejs/github-bot/issues/376#issuecomment-1458553582
Refs: https://github.com/isaacs/node-glob/issues/495
=> fix: use `dotRelative` glob option

package.json
@octokit/rest no longer supports Node.js 12. Our tests still pass, but our bot runs 14.x, so rather than get caught up some time if 12.x tests ever do start failing, let's drop support now.
=> chore: drop support for Node.js 12

package-lock.json, package.json, test/common.js, test/integration/event-relay-to-github-actions.test.js, test/integration/push-jenkins-update.test.js, test/unit/node-repo-owners.test.js, test/unit/node-repo.test.js, test/unit/push-jenkins-update.test.js
The underlying implementation changed and it now uses fetch, which nock  cannot mock. So introduce fetch-mock and change tests where relevant.
=>  chore: update @octokit/rest to 19.0.7

package-lock.json, package.json
This reverts commit 05ca7beba93b15276c60098275e012cd18ba283d.
Hopefully will fix https://github.com/nodejs/github-bot/issues/412
=> Revert "build(deps): bump glob from 10.3.1 to 10.3.3 (#409)"

package-lock.json, package.json
We can unpin it once the bot is running on Node.js 14.18 or newer.
Fixes: https://github.com/nodejs/build/issues/3720
=> fix: pin glob to 10.3.4

package-lock.json
This silences an `npm audit` warning.
=> chore: update semver 6.3.0 to 6.3.1 in package-lock.json

package.json
We are now running github-bot on Node.js 20 so let's stop testing on 14.x so we can update some packages that we've been holding off on.
Please don't land this. Let @richardlau land it. We *just* moved to 20.x and we want to give it some time to make sure we don't need to go back to the old server which is stuck at 14.x.
=> chore: update engines in package.json

package-lock.json, package.json, test/integration/event-relay-to-github-actions.test.js, test/integration/push-jenkins-update.test.js, test/unit/node-repo-owners.test.js, test/unit/node-repo.test.js, test/unit/push-jenkins-update.test.js
The API has changed to this update requires updates to our tests.
=> chore: update fetch-mock from 11.1.5 to 12.0.2

package-lock.json, package.json, test/integration/event-relay-to-github-actions.test.js, test/integration/ping.test.js, test/integration/push-jenkins-update.test.js, test/unit/node-owners.test.js, test/unit/node-repo-owners.test.js, test/unit/node-repo.test.js, test/unit/push-jenkins-update.test.js
This eliminates a (bogus) security warning about a tap dependency.
=> chore: move from tap to Node.js test runner
