nodejs/github-bot

- .editorconfig
- .gitignore
> add .editorconfig and include .env in .gitignore

- .travis.yml
> Enable Travis on this repo

- lib/pollTravis.js
This reverts commit 82f4437e7dafbef3dab57948744e2286e8b3fb02, reversing
changes made to 8e255d363c70f00ae2731d826576ab293e8afacc.
> Revert "Merge pull request #16 from Fishrock123/no-comment"

- scripts/display-travis-status.js
Adds the docker-node repo per https://github.com/nodejs/docker-node/issues/146
> Add docker-node repo

- lib/node-labels.js
- test/node-labels.test.js
> add meta label and more doc files

- lib/node-labels.js
- test/node-js-subsystem-labels.test.js
Fixes https://github.com/nodejs/github-bot/issues/64
> labels: "module" for doc/api/modules.md changes

- lib/node-labels.js
- test/_fixtures/repo-labels-page-2.json
- test/_fixtures/repo-labels.json
- test/integration/node-labels-webhook.test.js
- test/unit/node-labels.test.js
Refs: https://github.com/nodejs/CTC/issues/103
Not sure if this is all the places it should be changed, I did an `rg V8` and changed the places that seemed to make sense, but review would be much appreciated.
cc/ @addaleax
> Change "V8" labelling to "V8 Engine"

- lib/node-labels.js
- test/unit/node-labels.test.js
http2 does not exist in these branches
> labels: map dont-land-on-v4(6).x for http2

- scripts/display-travis-status.js
Fixes #166.
Fixes https://github.com/nodejs/string_decoder/issues/5.
> Add string_decoder to the enabled repos

- scripts/trigger-jenkins-build.js
- test/integration/trigger-jenkins-build.test.js
Refs: https://github.com/nodejs-private/secrets/pull/20
Refs: https://github.com/nodejs/github-bot/issues/175
Will now post comments upon pipeline builds being run
> jenkins: update to use pipeline

- test/unit/bot-username.test.js
> Add tests for bot-username module

- scripts/trigger-jenkins-build.js
> trigger-jenkins-build: DRY up event handlers

- scripts/trigger-jenkins-build.js
* Correct spelling of _occurred_.
* Capitalize first word.
* Add punctuation.
> revise failure text

- package-lock.json
- package.json
Update request to 2.88.0. This in turn updates extend to 3.0.2.
> update request to 2.88.0

- lib/node-labels.js
- test/unit/node-labels.test.js
Refs: #219 
/cc @vsemozhetbyt @richardlau
> labels: add "deprecations" label

- lib/push-jenkins-update.js
- scripts/trigger-jenkins-build.js
- test/integration/push-jenkins-update.test.js
This should work in any case, since we pass the defaults anyway
Also:
* Trigger bot note for `Lite-CI`
> Reduce parameter for ci job

- package-lock.json
Current version specified in lock file is susceptible to a security
vulnerability. Update.
> chore: Update eslint-utils

- app.js
- server.js
[As-is]
It not use the port value of dotenv.
[To-be]
It use the port value of dotenv.
> Fix to use the port value of dotenv

- package-lock.json
- package.json
This will address a GitHub security warning and will result in a clean
`npm audit`.
> chore: update dev dependency nodemon

- lib/node-repo.js
- test/unit/node-repo-owners.test.js
More log data makes it easier to understand when something fails.
> chore(owners): add more data to logs

- lib/node-repo.js
- test/unit/node-repo-owners.test.js
- test/unit/node-repo.test.js
getEvents is deprecated. Also use `number` instead of `issue_number` as
argument (`issue_number` is deprecated).
> chore: use listEvents instead of getEvents

- lib/node-labels.js
Refs: https://github.com/nodejs/node/pull/35093
cc @jasnell @nodejs/crypto
> feat: fix labels for refactored crypto subsystem

- .github/workflows/test.yml
- package.json
Closes https://github.com/nodejs/github-bot/issues/310
> Switch CI to pkgjs/action

- lib/push-jenkins-update.js
related: https://github.com/nodejs/node-core-utils/pull/652
cc @nodejs/v8-update
> feat: add v8 support

- lib/push-jenkins-update.js
- package-lock.json
- package.json
`createStatus()` is removed in @octokit/rest v18 so we replace it with `createCommitStatus()`
> chore: update @octokit/rest from v17 to v18

- lib/node-repo.js
- package-lock.json
- package.json
- test/integration/ping.test.js
request is no longer maintained.
> chore: remove request dependency

- package-lock.json
- package.json
Fixes: https://github.com/nodejs/build/issues/3720
@richardlau
> fix: pin glob to 10.3.12
